FROM python:3.12-alpine AS builder

    RUN pip install poetry==2.1.2

    ENV POETRY_NO_INTERACTION=1 \
        POETRY_VIRTUALENVS_IN_PROJECT=1 \
        POETRY_VIRTUALENVS_CREATE=1 \
        POETRY_CACHE_DIR=/tmp/poetry_cache

    WORKDIR /app

    COPY pyproject.toml poetry.lock ./

    RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --no-root --no-ansi


FROM python:3.12-alpine AS runtime

    ENV VIRTUAL_ENV=/app/.venv \
        PATH="/app/.venv/bin:$PATH"

    COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

    WORKDIR /app
    RUN rm -rf /app/*

    RUN mkdir /app/logs
